disabled_rules:
  - trailing_whitespace
  - line_length
  
opt_in_rules:
  - empty_count
  - explicit_init
  
excluded:
  - Pods
  - .build
  - DerivedData
  
line_length:
  warning: 120
  error: 200
  
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - i
    - j
    - x
    - y
    
force_cast: warning
force_try: warning
