# SwiftLint Configuration for Empy Swift

disabled_rules:
  - trailing_whitespace
  - todo  # Allow TODO comments during development

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_whitespace_closing_braces

excluded:
  - .build
  - Pods
  - Carthage
  - DerivedData
  - "*.generated.swift"

# Line length
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

# Type body length (for SwiftUI views that can be long)
type_body_length:
  warning: 400
  error: 600

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 60
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - to
    - db
    - ws
    - ok

# Nesting
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

# Force cast
force_cast: warning

# Force try
force_try: warning

reporter: "xcode"
